apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renci-update.fullname" . }}-secrets
  labels:
    {{- include "renci-update.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}